### ISSUE TITLE
Update third party Builds

### ISSUE THREAD

**Issue by Draise14** [overmindstudios/BlenderUpdater#19]
Is there an ability to also include forks/branches of Blender from other URL's? 

For example the fork Bforartists or builds from Graphicall. 

https://www.bforartists.de/content/download

How can you modify this to work with others? Do it have to be officially blender builds?

**Comment by tobkum** [comment]
Hey there!
There is no way to have it display builds other than the official ones. This would mean doing the URL scratching part for each different URL, which is a bit of work. I didn't even think of that feature since we're only using the official builds in-house. But feel free to tinker and submit a PR when you make it work!

Cheers

**Comment by tobkum** [comment]
It's done with BeautifulSoup - it scrapes the website for the links and outputs the list that gets displayed as the buttons. So you'd have to scan the graphicall site for the links and names of the builds.
